### PR TITLE
Support Rails till 5.0 (including)

### PR DESCRIPTION
**Pull request by Eric-Guo**
Appreciate if you could release a new version

### CODE REVIEW

**Comment by Eric-Guo** [comment]
@stefanvermaas I also upgrade zepto to the master version

**Comment by jeroenvisser101** [comment]
:+1:

**Comment by stefanvermaas** [comment]
Looks good to me! :+1: 

Thanks for you contribution!

**Comment by stefanvermaas** [comment]
It's pushed to RubyGems, reference: https://rubygems.org/gems/zepto-for-rails/versions/0.2.4. 

Cheers!

**Comment by Eric-Guo** [comment]
Thanks! :+1:

**Pull request merged**
